# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Option.create(name: 'Missions Experience')
Option.create(name: 'Experience Missions')
Option.create(name: 'Missions Connection')
Option.create(name: 'Mission Immersion')
Option.create(name: 'Missions Impact')
Option.create(name: 'Missions Outreach')
Option.create(name: 'Ignite')
Option.create(name: 'Missions Together')
Option.create(name: 'Reach')
Option.create(name: 'Connect')
Option.create(name: 'Bridge')
Option.create(name: 'Link')
Option.create(name: 'Partner')
Option.create(name: 'Journey')
Option.create(name: 'Adventure')
Option.create(name: 'Expedition')
Option.create(name: 'Trek')
Option.create(name: 'Embark')
Option.create(name: 'Short-term Missions')
Option.create(name: 'Cultivate Hope')
Option.create(name: 'Hope Projects')
Option.create(name: 'Live the Love')
Option.create(name: 'Missions Immersion')
Option.create(name: 'Agape Missions')
Option.create(name: 'World Reaching Missions')
Option.create(name: 'Serve Trips')
Option.create(name: 'Life Trips')
Option.create(name: 'Missions Effect')
Option.create(name: 'Missions Encounter')
Option.create(name: 'Missions Voyage')
Option.create(name: 'Missions Exchange')
Option.create(name: 'Step-Out in Missions')
Option.create(name: 'Step-Up to Missions')
Option.create(name: 'Pitch-In Missions')
Option.create(name: 'Engage Missions')
Option.create(name: 'Encounter Missions')
Option.create(name: 'Eternal Missions')
Option.create(name: 'Advance Missions')
Option.create(name: 'Forward Missions')
Option.create(name: 'Legacy Missions')
Option.create(name: 'Great Commission Missions')
Option.create(name: 'Chosen')
Option.create(name: 'Choose')
Option.create(name: 'Send')
Option.create(name: 'Converge')
Option.create(name: 'Complete Missions')
Option.create(name: 'Missions Together')
Option.create(name: 'Better Together')
Option.create(name: 'Missions Accomplished')
Option.create(name: 'Build the Bond')
Option.create(name: 'Hand in Hand Missions')
Option.create(name: 'Side by Side Missions')
Option.create(name: 'One Voice Missions')
Option.create(name: 'Experience Missions')
Option.create(name: 'Missions Makers')
Option.create(name: 'Bridge')
Option.create(name: 'Building Bridges')
Option.create(name: 'Missions Restore')
Option.create(name: 'Alliance')
Option.create(name: 'Missions Collective')
Option.create(name: 'Unified Missions')
Option.create(name: 'In His Service')
Option.create(name: 'Missions Unite')